<?php

namespace ContainerP8MoxJ6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QSRc9DPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qSRc9DP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qSRc9DP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\Admin\\VehicleController::create' => ['privates', '.service_locator.ESajd_W', 'get_ServiceLocator_ESajdWService', true],
            'App\\Controller\\Admin\\VehicleController::index' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\AvailabilityController::create' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\AvailabilityController::delete' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\AvailabilityController::deleteConfirm' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\AvailabilityController::edit' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\AvailabilityController::show' => ['privates', '.service_locator.tQ._l3s', 'get_ServiceLocator_TQ_L3sService', true],
            'App\\Controller\\ContactController::contact' => ['privates', '.service_locator.uVvF4gL', 'get_ServiceLocator_UVvF4gLService', true],
            'App\\Controller\\SearchController::generateDateRanges' => ['privates', '.service_locator.G2fKdh.', 'get_ServiceLocator_G2fKdh_Service', true],
            'App\\Controller\\SearchController::searchAvailability' => ['privates', '.service_locator..2NzcIV', 'get_ServiceLocator__2NzcIVService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\Admin\\VehicleController:create' => ['privates', '.service_locator.ESajd_W', 'get_ServiceLocator_ESajdWService', true],
            'App\\Controller\\Admin\\VehicleController:index' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\AvailabilityController:create' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\AvailabilityController:delete' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\AvailabilityController:deleteConfirm' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\AvailabilityController:edit' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\AvailabilityController:show' => ['privates', '.service_locator.tQ._l3s', 'get_ServiceLocator_TQ_L3sService', true],
            'App\\Controller\\ContactController:contact' => ['privates', '.service_locator.uVvF4gL', 'get_ServiceLocator_UVvF4gLService', true],
            'App\\Controller\\SearchController:generateDateRanges' => ['privates', '.service_locator.G2fKdh.', 'get_ServiceLocator_G2fKdh_Service', true],
            'App\\Controller\\SearchController:searchAvailability' => ['privates', '.service_locator..2NzcIV', 'get_ServiceLocator__2NzcIVService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\Admin\\VehicleController::create' => '?',
            'App\\Controller\\Admin\\VehicleController::index' => '?',
            'App\\Controller\\AvailabilityController::create' => '?',
            'App\\Controller\\AvailabilityController::delete' => '?',
            'App\\Controller\\AvailabilityController::deleteConfirm' => '?',
            'App\\Controller\\AvailabilityController::edit' => '?',
            'App\\Controller\\AvailabilityController::show' => '?',
            'App\\Controller\\ContactController::contact' => '?',
            'App\\Controller\\SearchController::generateDateRanges' => '?',
            'App\\Controller\\SearchController::searchAvailability' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\Admin\\VehicleController:create' => '?',
            'App\\Controller\\Admin\\VehicleController:index' => '?',
            'App\\Controller\\AvailabilityController:create' => '?',
            'App\\Controller\\AvailabilityController:delete' => '?',
            'App\\Controller\\AvailabilityController:deleteConfirm' => '?',
            'App\\Controller\\AvailabilityController:edit' => '?',
            'App\\Controller\\AvailabilityController:show' => '?',
            'App\\Controller\\ContactController:contact' => '?',
            'App\\Controller\\SearchController:generateDateRanges' => '?',
            'App\\Controller\\SearchController:searchAvailability' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
