<?php

namespace ContainerXSJIqem;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator___BPqHiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator...bPqHi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator...bPqHi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'image' => ['privates', '.errored..service_locator...bPqHi.App\\Entity\\Image', NULL, 'Cannot autowire service ".service_locator...bPqHi": it needs an instance of "App\\Entity\\Image" but this type has been excluded in "config/services.yaml".'],
            'vehicle' => ['privates', '.errored..service_locator...bPqHi.App\\Entity\\Vehicle', NULL, 'Cannot autowire service ".service_locator...bPqHi": it needs an instance of "App\\Entity\\Vehicle" but this type has been excluded in "config/services.yaml".'],
        ], [
            'doctrine' => '?',
            'image' => 'App\\Entity\\Image',
            'vehicle' => 'App\\Entity\\Vehicle',
        ]);
    }
}
