<?php

namespace ContainerEwYYFxw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QBzdZlnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.QBzdZln' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QBzdZln'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'vehicle' => ['privates', '.errored..service_locator.QBzdZln.App\\Entity\\Vehicle', NULL, 'Cannot autowire service ".service_locator.QBzdZln": it needs an instance of "App\\Entity\\Vehicle" but this type has been excluded in "config/services.yaml".'],
        ], [
            'doctrine' => '?',
            'vehicle' => 'App\\Entity\\Vehicle',
        ]);
    }
}
