<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQeWb3Ds\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQeWb3Ds/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerQeWb3Ds.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerQeWb3Ds\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerQeWb3Ds\App_KernelTestDebugContainer([
    'container.build_hash' => 'QeWb3Ds',
    'container.build_id' => 'b5248cc7',
    'container.build_time' => 1715731728,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQeWb3Ds');
