<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], [], []],
    'vehicle_index' => [[], ['_controller' => 'App\\Controller\\VehicleController::index'], [], [['text', '/vehicules']], [], [], []],
    'vehicle_create' => [[], ['_controller' => 'App\\Controller\\VehicleController::create'], [], [['text', '/vehicules/ajouter']], [], [], []],
    'availability_create' => [[], ['_controller' => 'App\\Controller\\AvailabilityController::create'], [], [['text', '/disponibilites/ajouter']], [], [], []],
    'availability_show' => [['slug'], ['_controller' => 'App\\Controller\\AvailabilityController::show'], ['slug' => '[a-z0-9\\-]+'], [['variable', '/', '[a-z0-9\\-]+', 'slug', true], ['text', '/disponibilites']], [], [], []],
    'availability_edit' => [['slug', 'id'], ['_controller' => 'App\\Controller\\AvailabilityController::edit'], ['slug' => '[a-z0-9\\-]+', 'id' => '\\d+'], [['text', '/modifier'], ['variable', '/', '\\d+', 'id', true], ['variable', '/', '[a-z0-9\\-]+', 'slug', true], ['text', '/disponibilites']], [], [], []],
    'availability_delete_confirm' => [['slug', 'id'], ['_controller' => 'App\\Controller\\AvailabilityController::deleteConfirm'], ['slug' => '[a-z0-9\\-]+', 'id' => '\\d+'], [['text', '/confirmer'], ['variable', '/', '\\d+', 'id', true], ['variable', '/', '[a-z0-9\\-]+', 'slug', true], ['text', '/disponibilites']], [], [], []],
    'availability_delete' => [['slug', 'id'], ['_controller' => 'App\\Controller\\AvailabilityController::delete'], ['slug' => '[a-z0-9\\-]+', 'id' => '\\d+'], [['text', '/supprimer'], ['variable', '/', '\\d+', 'id', true], ['variable', '/', '[a-z0-9\\-]+', 'slug', true], ['text', '/disponibilites']], [], [], []],
    'search_availability' => [[], ['_controller' => 'App\\Controller\\SearchController::searchAvailability'], [], [['text', '/recherche']], [], [], []],
];
