<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOlhf8xV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOlhf8xV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOlhf8xV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOlhf8xV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOlhf8xV\App_KernelDevDebugContainer([
    'container.build_hash' => 'Olhf8xV',
    'container.build_id' => '046fc4ad',
    'container.build_time' => 1718027154,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOlhf8xV');
