<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEwYYFxw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEwYYFxw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEwYYFxw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEwYYFxw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEwYYFxw\App_KernelDevDebugContainer([
    'container.build_hash' => 'EwYYFxw',
    'container.build_id' => '843883a9',
    'container.build_time' => 1718102567,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEwYYFxw');
