<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5G4vI7i\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5G4vI7i/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5G4vI7i.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5G4vI7i\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5G4vI7i\App_KernelDevDebugContainer([
    'container.build_hash' => '5G4vI7i',
    'container.build_id' => 'a59517f9',
    'container.build_time' => 1717599760,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container5G4vI7i');
